version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: order-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_management
    ports:
      - "3306:3306"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    # Removendo healthcheck complexo que pode falhar no Windows
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    container_name: order-app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=order_management
      - DB_USER=root
      - DB_PASS=root
    depends_on:
      - db
